### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by AtomicVar** [premieroctet/firstcommit#37]
<img width="502" alt="图片" src="https://user-images.githubusercontent.com/22856433/207583750-47ab3b39-f673-4a8c-abd6-3b05008e1596.png">

The website is not working.

**Comment by iqfareez** [comment]
I have similar issue, perhaps the GitHub token has expired. But anyway, you can fork the project and deploy on your own. For example, here's mine: https://firstcommit.vercel.app/

**Comment by tlenclos** [comment]
Hello there ! We upgraded the project to use Next.js and did some minor improvements like handling og:image preview.

Everything is now deployed there https://firstcommit.app
